version: '3.3'
services:
  php:
    container_name: NUTRITIONS_PHP
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    env_file:
        - .env
    networks:
      - nutritions-network

  api:
    image: nginx:alpine
    container_name: NUTRITIONS_API
    ports:
      - ${APP_SSL_PORT}:443
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - nutritions-network

  db:
    image: mysql
    container_name: NUTRITIONS_DB
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERICE_TAGS: ${APP_ENV}
      SERIVE_NAME: 'mysql'
    env_file:
      - .env
    networks:
      - nutritions-network
    volumes:
      - dbdata:/var/lib/mysql/

  mailhog:
    image: mailhog/mailhog
    container_name: NUTRITIONS_MAILHOG
    logging:
      driver: 'none'
    ports:
      - ${MAIL_PORT}:1025
      - ${MAIL_UI_PORT}:8025
    networks:
      - nutritions-network

# Docker Networks
networks:
  nutritions-network:
    driver: bridge

# Docker Volumes
volumes:
  dbdata:
    driver: local
